# Generated by Django 4.2.1 on 2023-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_purchase_price_stock_average_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purchase',
            field=models.BooleanField(default=False),
        ),
    ]
