# Generated by Django 4.2.1 on 2023-06-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_transaction_stock_symbol_alter_transaction_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(to='dashboard.stock'),
        ),
    ]
