# Generated by Django 4.2.1 on 2023-06-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profile_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='watchlist',
        ),
    ]
