# Generated by Django 4.2.1 on 2023-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_profile_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(to='dashboard.stock'),
        ),
    ]
